### ISSUE TITLE
大佬，代码格式不是UTF-8, 貌似有些不是很通用呢，我这边用vscode打开，中文注释都是乱码

### ISSUE THREAD

**Issue by chenyingchun0312** [mysterywolf/RT-Thread-wrapper-of-uCOS-III#1]
大佬，代码格式不是UTF-8, 貌似有些不是很痛用呢

**Comment by mysterywolf** [comment]
这个是基于KEIL平台编译的，KEIL平台对UTF-8格式支持并不是很好，**建议你可以将VSCODE编码格式改为GB2312**。而且uCOS-III原版本身即为ANSI编码。

**Comment by mysterywolf** [comment]
而且 STM32 HAL库文件以及RTT的文件都是采用ANSI编码 并非UTF-8编码。

**Comment by mysterywolf** [comment]
设置GB2312可以参考 https://jingyan.baidu.com/article/5552ef4792ac5a518ffbc996.html

**Comment by chenyingchun0312** [comment]
我这边使用notepadd++打开了STM32 HAL库，以及RTT的源码，好像看到的都是UTF-8呢， 另外， MDK对UTF-8编码已经可以很好的支持了呢，不过都没有关系哈，只是我个人觉得UTF-8比较通用而已 @mysterywolf

**Comment by mysterywolf** [comment]
HAL库以及RTT源码并非UTF-8编码 而是采用的是ANSI编码 只不过他们没有使用其他国家的文字，这两种编码在解码ASCII时是可以正确显示的，因此在你的vscode中即便使用utf编码也可以正确打开。你可以采用记事本查看并点击另存为，你就会发现当前的编码格式为ANSI编码格式。虽然MDK本身是支持UTF-8，但是如果MDK混合这两种编码文件可并尝试对UTF-8的文件修改后再编译的话就会出错。因为emwin的汉字就是要求采用UTF-8编码，这在实际操作过程中挺烦人的，稍微改一点UTF-8编码的文件就需要重新保存为UTF-8才可以。

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/88376332-c11c4080-cdcf-11ea-89a6-926864979c57.png)
如图为ucos源码采用的编码格式

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/88376479-13f5f800-cdd0-11ea-9fed-84315341ab31.png)
如图为RTT源码的编码方式

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/88376537-2ff99980-cdd0-11ea-93cd-300849d2d891.png)
如图为RTT源码的编码格式
