### ISSUE TITLE
请大佬增加对UCOS-II兼容层的支持

### ISSUE THREAD

**Issue by HelloCoderman** [mysterywolf/RT-Thread-wrapper-of-uCOS-III#2]
请增加对UCOS-II兼容层的支持，因为现在很多和项目还是使用的是ucos-ii，至于ucos-iii感觉使用的人不多

**Comment by mysterywolf** [comment]
> 请增加对UCOS-II兼容层的支持，因为现在很多和项目还是使用的是ucos-ii，至于ucos-iii感觉使用的人不多

好 因为ucos-ii和iii有共同性 我想着等ucosiii的兼容层沉淀一下看看有什么问题 再做ucosii，没想到这么快就有人要ucos ii的兼容层了，没问题 这个项目给我个star呗😀

**Comment by HelloCoderman** [comment]
OK，其实我们更需要个能将RT的设备层用上，然后内核使用ucos-ii，但是感觉在剥离的时候不是特别方便。

**Comment by mysterywolf** [comment]
你好 我已经开始施工了https://github.com/mysterywolf/RT-Thread-wrapper-of-uCOS-II

**Comment by HelloCoderman** [comment]
佩服大侠的精神，想不到会这么快相应，赞一个。。

**Comment by xby13030199338** [comment]
太厉害了！

**Comment by mysterywolf** [comment]
uCOS-II兼容层已经可以使用了

**Comment by xby13030199338** [comment]
感谢！


Meco Man <notifications@github.com> 于2020年12月25日周五 上午2:58写道：
